"""empty message

Revision ID: 025009c92657
Revises: 
Create Date: 2024-01-30 21:41:39.416191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '025009c92657'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classes', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('correct_answer', sa.Text(), nullable=True))
        batch_op.drop_column('answers')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answers', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('correct_answer')
        batch_op.drop_column('classes')

    # ### end Alembic commands ###
